Repository KasperskyLab/Kaspresso, pull requests merged in 2020-09, with the labels that each got.

#189 Issue #180 Bump libraries versions
  adb-server/common/src/main/java/com/kaspresky/adbserver/log/LoggerFactory.kt
  adb-server/connection/src/main/java/com/kaspersky/adbserver/implementation/ConnectionClientImplBySocket.kt
  adb-server/connection/src/main/java/com/kaspersky/adbserver/implementation/transferring/SocketMessagesTransferring.kt
  adb-server/desktop-device-connection/src/main/java/com/kaspersky/adbserver/DesktopDeviceSocketConnectionForwardImpl.kt
  adb-server/desktop/src/main/java/com/kaspersky/adbserver/Desktop.kt
  adb-server/desktop/src/main/java/com/kaspersky/adbserver/DeviceMirror.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  gradle/wrapper/gradle-wrapper.properties
  kaspresso/kaspresso-framework/src/main/kotlin/com/kaspersky/kaspresso/device/network/NetworkImpl.kt
  kaspresso/kaspresso-framework/src/main/kotlin/com/kaspersky/kaspresso/docloc/SystemLanguage.kt
  kaspresso/kaspresso-framework/src/main/kotlin/com/kaspersky/kaspresso/interceptors/watcher/kautomator/impl/logging/LoggingObjectWatcherInterceptor.kt
  kaspresso/kaspresso-framework/src/main/kotlin/com/kaspersky/kaspresso/interceptors/watcher/testcase/impl/composite/TestRunCompositeWatcherInterceptor.kt
  kaspresso/kaspresso-framework/src/main/kotlin/com/kaspersky/kaspresso/internal/systemscreen/WiFiSettingsScreen.kt
  kaspresso/kaspresso-framework/src/main/kotlin/com/kaspersky/kaspresso/uiobjectloader/UiObjectLoaderProviderImpl.kt
  kaspresso/kaspresso-sample/src/main/kotlin/com/kaspersky/kaspressample/flaky/CommonFlakyActivity.kt
  kautomator/kautomator-framework/src/main/kotlin/com/kaspersky/components/kautomator/intercept/exception/UnfoundedUiObjectException.kt
  kautomator/kautomator-framework/src/main/kotlin/com/kaspersky/components/kautomator/system/UiSystemActions.kt
Labels: enhancement

#201 issue #195 update publishing scripts
  adb-server/adbserver-device/gradle.properties
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/publishing/Publishing.kt
  gradle.properties
  kaspresso/gradle.properties
  kautomator/build.gradle.kts
  kautomator/gradle.properties
Labels: bug

#196 Issue/release 1 2 0
  README.md
Labels: documentation
